export const FPS = 30;
export const scenes = [
  {
    id: "intro",
    seconds: 6,
    eyebrow: "INTRODUCING BRIDGE",
    title: "Your agents.\nOne control room.",
    body: "From a first thought to a reviewed change.",
    source: "README.md",
  },
  {
    id: "providers",
    seconds: 7,
    eyebrow: "01 / WORK TOGETHER",
    title: "Pick the mind.\nKeep the thread.",
    body: "Claude Code, Codex, Cursor, OpenCode. Switch providers inside a conversation.",
    note: "The provider restarts. Your history stays.",
    source: "landing/app/components/FeatureScroll.tsx",
  },
  {
    id: "mission",
    seconds: 7,
    eyebrow: "02 / MISSION CONTROL",
    title: "See the whole\nteam at work.",
    body: "Live conversations, plans and approvals. One window for every moving part.",
    image: "mission-control.webp",
    source: "README.md",
  },
  {
    id: "delegate",
    seconds: 7,
    eyebrow: "03 / ORCHESTRATION",
    title: "One goal.\nThe right roles.",
    body: "Route research, implementation and verification to the right capability tier.",
    source: "docs/delegation-policy.md",
  },
  {
    id: "worktrees",
    seconds: 7,
    eyebrow: "04 / ISOLATED WORKSPACES",
    title: "Room to try.\nSpace to build.",
    body: "Parallel tasks get their own branches and checkouts. Review, adopt or discard.",
    source: "landing/app/content/appScenes.ts",
  },
  {
    id: "review",
    seconds: 6,
    eyebrow: "05 / REVIEW & APPROVALS",
    title: "Every change.\nIn plain sight.",
    body: "Inspect diffs and risk labels. Approve actions beyond the agreed scope.",
    image: "review-diffs.webp",
    source: "README.md",
  },
  {
    id: "verify",
    seconds: 7,
    eyebrow: "06 / COMPLETION GATES",
    title: "A second set\nof eyes.",
    body: "Require checks and independent verification before adopting the work.",
    source: "landing/app/content/appScenes.ts",
  },
  {
    id: "history",
    seconds: 7,
    eyebrow: "07 / CONTINUITY",
    title: "Pick up where\nyou left off.",
    body: "Local history. Forks and rewind. Checkpoints when context fills.",
    note: "Original events remain inspectable.",
    source: "landing/app/components/FeatureScroll.tsx",
  },
  {
    id: "memory",
    seconds: 6,
    eyebrow: "08 / MEMORY",
    title: "Your way of\nworking, saved.",
    body: "Carry preferences, conventions and project decisions into future sessions.",
    source: "README.md",
  },
  {
    id: "browser",
    seconds: 6,
    eyebrow: "09 / BROWSER BRIDGE",
    title: "Your browser.\nYour permission.",
    body: "Give agents temporary access to one approved, signed-in tab.",
    note: "Review actions. Take over or detach at any time.",
    source: "docs/authenticated-browser-bridge.md",
  },
  {
    id: "extend",
    seconds: 6,
    eyebrow: "10 / MAKE IT YOURS",
    title: "Bring your\nbest tools.",
    body: "Add skills, plugins and agent roles. Connect project work to GitHub.",
    source: "landing/app/components/FeatureScroll.tsx; README.md",
  },
  {
    id: "prompts",
    seconds: 6,
    eyebrow: "11 / PROMPT STUDIO",
    title: "Better guidance.\nOn your terms.",
    body: "Review proposed instruction changes and keep revision history.",
    source: "src/components/PromptStudio.tsx",
  },
  {
    id: "automations",
    seconds: 6,
    eyebrow: "12 / AUTOMATIONS",
    title: "Put routine\nwork on repeat.",
    body: "Schedule triage, maintenance and recurring tasks with the same review gates.",
    source: "landing/app/components/FeatureScroll.tsx",
  },
  {
    id: "usage",
    seconds: 6,
    eyebrow: "13 / USAGE & LIMITS",
    title: "Know where\nthe tokens go.",
    body: "Track provider usage, cost, cache savings and context pressure.",
    image: "usage.webp",
    source: "README.md",
  },
  {
    id: "fleet",
    seconds: 6,
    eyebrow: "14 / AGENT FLEET",
    title: "A terminal for\nevery agent.",
    body: "Run the CLIs in a terminal grid, organized by checkout.",
    image: "agent-fleet.webp",
    source: "README.md",
  },
  {
    id: "outro",
    seconds: 6,
    eyebrow: "BRIDGE",
    title: "Bring your agents.\nBuild what’s next.",
    body: "Your subscriptions. Your projects. One place.",
    source: "README.md",
  },
] as const;
export const timeline = scenes.map((scene, i) => ({
  ...scene,
  from: scenes.slice(0, i).reduce((sum, s) => sum + s.seconds * FPS, 0),
  duration: scene.seconds * FPS,
}));
export const DURATION = scenes.reduce((sum, s) => sum + s.seconds * FPS, 0);
