import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, ChevronDown, Download, ExternalLink, LoaderCircle, RotateCcw, Search, ShieldCheck, Trash2, X } from "lucide-react";
import { bridgeApi } from "../api";
import type { CommunitySkill, SkillAction, SkillActionResult, SkillCatalog, SkillPreview, SkillProvider } from "../types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogPanel, DialogTitle } from "@/components/ui/dialog";

const providerLabel = (provider: SkillProvider) => provider === "codex" ? "Codex" : provider === "claude" ? "Claude" : "OpenCode";
const compactNumber = new Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 });

export function SkillMarketplace() {
  const [catalog, setCatalog] = useState<SkillCatalog>();
  const [scope, setScope] = useState<"community" | "personal">("community");
  const [provider, setProvider] = useState<SkillProvider | "all">("all");
  const [query, setQuery] = useState("");
  const [expanded, setExpanded] = useState<string>();
  const [preview, setPreview] = useState<SkillPreview>();
  const [results, setResults] = useState<SkillActionResult[]>([]);
  const [failure, setFailure] = useState<string>();
  const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { try { setCatalog(await bridgeApi.skillCatalog()); setFailure(undefined); } catch (error) { setFailure(error instanceof Error ? error.message : String(error)); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const community = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return (catalog?.community ?? []).filter(skill => (provider === "all" || skill.compatibility.includes(provider)) && (!needle || `${skill.name} ${skill.description} ${skill.source} ${skill.categories.join(" ")}`.toLowerCase().includes(needle)));
  }, [catalog, provider, query]);
  const personal = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return (catalog?.personal ?? []).filter(skill => (provider === "all" || skill.providers.includes(provider)) && (!needle || `${skill.name} ${skill.description}`.toLowerCase().includes(needle)));
  }, [catalog, provider, query]);
  const request = async (skill: CommunitySkill, action: SkillAction, targets: SkillProvider[]) => {
    setBusy(true); setResults([]); setFailure(undefined);
    try { setPreview(await bridgeApi.previewSkillChange(skill.id, action, targets)); }
    catch (error) { setFailure(error instanceof Error ? error.message : String(error)); }
    finally { setBusy(false); }
  };
  const execute = async () => {
    if (!preview) return;
    setBusy(true);
    try { setResults(await bridgeApi.executeSkillChange(preview.confirmationId)); setPreview(undefined); await refresh(); }
    catch (error) { setFailure(error instanceof Error ? error.message : String(error)); setPreview(undefined); }
    finally { setBusy(false); }
  };
  return <div className="h-full min-h-0 overflow-y-auto">
    <main className="mx-auto w-full max-w-5xl px-3 pb-16 pt-8 sm:px-6 sm:pt-12">
      <div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><h1 className="font-display text-[26px] font-semibold tracking-[-0.025em] text-foreground sm:text-[32px]">Skills</h1><p className="mt-1.5 text-[13.5px] leading-relaxed text-muted-foreground">Curated capabilities for Codex, Claude, and OpenCode, with explicit trust and rollback</p></div><span className="mt-2 shrink-0 rounded-full border border-border bg-muted px-2.5 py-1 text-[10px] font-medium text-muted-foreground">{catalog?.community.length ?? 0} curated</span></div>
      <div className="relative mt-6"><Search className="pointer-events-none absolute left-3.5 top-1/2 z-10 -translate-y-1/2 text-muted-foreground" size={14}/><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search skills, publishers, or capabilities" className="h-10 rounded-full pl-10 text-[13px]"/></div>
      <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="u-segmented">{(["community", "personal"] as const).map(value => <button key={value} data-active={scope === value} onClick={() => setScope(value)} className="u-segmented-item capitalize">{value}</button>)}</div><div className="u-segmented">{(["all", "codex", "claude", "opencode"] as const).map(value => <button key={value} data-active={provider === value} onClick={() => setProvider(value)} className="u-segmented-item">{value === "all" ? "All" : providerLabel(value)}</button>)}</div></div>
      {failure && <div className="mt-3 flex items-start gap-2 rounded-xl border border-destructive/30 bg-destructive/10 px-3 py-2 text-[10.5px] text-destructive"><AlertTriangle className="mt-0.5 shrink-0" size={12}/><span className="min-w-0 break-words">{failure}</span></div>}
      {!catalog && <div className="flex min-h-56 items-center justify-center gap-2 text-xs text-muted-foreground"><LoaderCircle className="animate-spin" size={15}/>Reading local capabilities…</div>}
      {catalog && scope === "community" && <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">{community.map(skill => {
        const open = expanded === skill.id;
        const installed = skill.providerStates.filter(state => state.installed);
        const installable = skill.providerStates.filter(state => !state.installed && !state.receiptError).map(state => state.provider);
        return <article key={skill.id} className={`rounded-2xl border bg-card px-4 py-3.5 transition-colors duration-200 ${open ? "border-input bg-accent" : "border-border hover:border-input hover:bg-accent"}`}>
          <button type="button" onClick={() => setExpanded(open ? undefined : skill.id)} className="flex w-full items-start gap-3.5 text-left"><div className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-[12px] border border-border bg-accent font-display text-[11px] font-semibold text-foreground">{skill.name.slice(0, 2).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="truncate text-[13.5px] font-semibold tracking-[-0.008em] text-foreground">{skill.name}</h3>{skill.official && <ShieldCheck size={12} className="shrink-0 text-info" aria-label="Official publisher"/>}<span className={`inline-flex shrink-0 items-center gap-1 rounded-full border px-1.5 py-0.5 text-[8.5px] font-medium uppercase tracking-[0.04em] ${skill.risk === "low" ? "border-success/30 bg-success/10 text-success" : skill.risk === "elevated" ? "border-destructive/30 bg-destructive/10 text-destructive" : "border-warning/30 bg-warning/10 text-warning"}`}>{skill.risk} risk</span></div><p className={`mt-1 text-[11.5px] leading-[1.55] text-muted-foreground ${open ? "" : "truncate"}`}>{skill.description}</p><div className="mt-2 flex flex-wrap items-center gap-x-2 gap-y-1 text-[10px] text-muted-foreground/70"><span className="font-mono">{compactNumber.format(skill.installs)}</span><span>installs</span><span className="text-muted-foreground/40">·</span><span className="truncate">{skill.source}</span>{installed.length > 0 && <><span className="text-muted-foreground/40">·</span><span className="text-success">Installed: {installed.map(state => providerLabel(state.provider)).join(" + ")}</span></>}</div></div><ChevronDown size={13} className={`mt-1 shrink-0 text-muted-foreground/70 transition-transform ${open ? "rotate-180" : ""}`}/></button>
          {open && <div className="mt-3 rounded-xl border border-border bg-background p-3.5 text-[10.5px] text-muted-foreground sm:ml-[50px]"><p className="mb-1.5 text-[9px] font-semibold uppercase tracking-[0.12em] text-muted-foreground/70">Estimated access</p><div className="flex flex-wrap gap-1.5">{skill.permissions.map(permission => <span key={permission} className="rounded-full border border-border bg-card px-2 py-0.5">{permission}</span>)}</div><p className="mt-2 leading-relaxed">{skill.riskSummary}</p>{skill.providerStates.filter(state => state.receiptError).map(state => <p key={state.provider} className="mt-2 break-words rounded-lg border border-destructive/30 bg-destructive/10 px-2 py-1.5 text-destructive"><b>{providerLabel(state.provider)}:</b> {state.receiptError}</p>)}<div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 font-mono text-[9px]"><a href={skill.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-info hover:text-foreground">Source <ExternalLink size={9}/></a><span>pin {skill.pinnedRef.slice(0, 10)}</span><span>{skill.fileCount} files</span><span>{catalog.installer}</span></div><div className="mt-3 flex flex-wrap gap-1.5">{installable.map(target => <Button key={target} size="xs" disabled={busy} onClick={() => void request(skill, "install", [target])}><Download size={10}/>Install for {providerLabel(target)}</Button>)}{installable.length > 1 && <Button size="xs" variant="secondary" disabled={busy} onClick={() => void request(skill, "install", installable)}>Install for all</Button>}{installed.filter(state => state.managed && state.updateAvailable).map(state => <Button key={`update-${state.provider}`} size="xs" disabled={busy} onClick={() => void request(skill, "install", [state.provider])}><Download size={10}/>Update {providerLabel(state.provider)}</Button>)}{installed.filter(state => state.managed && state.rollbackAvailable).map(state => <Button key={`rollback-${state.provider}`} size="xs" variant="secondary" disabled={busy} onClick={() => void request(skill, "rollback", [state.provider])}><RotateCcw size={10}/>Rollback {providerLabel(state.provider)}</Button>)}{installed.filter(state => state.managed).map(state => <Button key={`remove-${state.provider}`} size="xs" variant="ghost" disabled={busy} onClick={() => void request(skill, "uninstall", [state.provider])}><Trash2 size={10}/>Remove {providerLabel(state.provider)}</Button>)}</div></div>}
        </article>;
      })}</div>}
      {catalog && scope === "personal" && <section className="mt-5"><div className="mb-4 rounded-2xl border border-info/30 bg-info/10 px-4 py-3 text-[11.5px] leading-relaxed text-muted-foreground"><b className="font-medium text-foreground">Yours, untouched.</b> Personal Skills are discovered locally and shown separately. Bridge never updates, replaces, or removes them.</div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">{personal.map(skill => <article key={skill.id} className="rounded-2xl border border-border bg-card px-4 py-3.5 transition-colors duration-200 hover:border-input hover:bg-accent"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate text-[13.5px] font-semibold tracking-[-0.008em] text-foreground">{skill.name}</h3><p className="mt-1 truncate text-[11.5px] leading-[1.55] text-muted-foreground">{skill.description || "Local skill"}</p></div><div className="flex shrink-0 flex-wrap justify-end gap-1">{skill.providers.map(item => <span key={item} className="rounded-full border border-border bg-muted px-2 py-0.5 text-[9px] text-muted-foreground">{providerLabel(item)}</span>)}</div></div></article>)}</div>{personal.length === 0 && <p className="py-16 text-center text-xs text-muted-foreground/70">No matching Personal Skills.</p>}</section>}
      {!!results.length && <div className="u-overlay-strong fixed bottom-5 right-5 z-40 w-80 max-w-[calc(100vw-2.5rem)] rounded-2xl p-3.5"><button onClick={() => setResults([])} className="absolute right-2.5 top-2.5 text-muted-foreground transition-colors hover:text-foreground"><X size={12}/></button>{results.map(result => <p key={`${result.provider}:${result.action}`} className="flex gap-2 py-1 text-[10.5px] text-muted-foreground">{result.success ? <Check size={12} className="shrink-0 text-success"/> : <AlertTriangle size={12} className="shrink-0 text-destructive"/>}<span className="min-w-0 break-words"><b className="text-foreground">{providerLabel(result.provider)}:</b> {result.error ?? result.message}</span></p>)}</div>}
    </main>
    <Dialog open={!!preview} onOpenChange={open => { if (!open && !busy) setPreview(undefined); }}>{preview && <DialogContent showCloseButton={!busy}><DialogHeader><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 shrink-0 text-warning" size={16}/><div><DialogTitle className="font-display text-base font-medium text-foreground">Confirm {preview.action}</DialogTitle><DialogDescription className="mt-1 text-[11px] leading-5">Review the exact source and requested access before Bridge changes the selected providers.</DialogDescription></div></div></DialogHeader><DialogPanel className="py-0"><dl className="grid grid-cols-[72px_1fr] gap-x-3 gap-y-2 rounded-xl border border-border bg-muted p-3 text-[10px] sm:grid-cols-[88px_1fr]"><dt className="text-muted-foreground">Skill</dt><dd className="break-words text-foreground">{preview.skill.name}</dd><dt className="text-muted-foreground">Source</dt><dd className="break-all text-muted-foreground">{preview.skill.sourceUrl}</dd><dt className="text-muted-foreground">Pinned ref</dt><dd className="break-all font-mono text-muted-foreground">{preview.skill.pinnedRef}</dd><dt className="text-muted-foreground">Targets</dt><dd className="text-muted-foreground">{preview.targets.map(providerLabel).join(" + ")}</dd><dt className="text-muted-foreground">Permissions</dt><dd className="break-words text-muted-foreground">{preview.skill.permissions.join(", ")}</dd><dt className="text-muted-foreground">Risk</dt><dd className="break-words text-muted-foreground">{preview.skill.risk}: {preview.skill.riskSummary}</dd><dt className="text-muted-foreground">Files</dt><dd className="text-muted-foreground">{preview.skill.fileCount} via {preview.installer}</dd></dl><ul className="mt-3 space-y-1 text-[10px] text-muted-foreground">{preview.changes.map(change => <li key={change} className="break-words">• {change}</li>)}</ul></DialogPanel><DialogFooter variant="bare"><Button variant="ghost" disabled={busy} onClick={() => setPreview(undefined)}>Cancel</Button><Button disabled={busy} onClick={() => void execute()}>{busy && <LoaderCircle className="animate-spin" size={12}/>}Confirm once</Button></DialogFooter></DialogContent>}</Dialog>
  </div>;
}
