//! Generated-artifact rendering: JSON Schemas for the envelope and handshake
//! types, registry tables for methods and error codes, and TypeScript types
//! converted *from those schemas* so there is a single source of truth.
//!
//! Regenerate with `cargo run -p bridge-protocol --bin generate-protocol-artifacts`.
//! Drift tests below fail whenever the checked-in artifacts are stale.

use std::collections::BTreeMap;

use schemars::schema_for;
use serde_json::{json, Map, Value};

use crate::envelope::{CancelParams, RpcNotification, RpcRequest, RpcResponse};
use crate::error::ErrorCode;
use crate::handshake::{HandshakeRequest, HandshakeResponse, PROTOCOL_VERSION};
use crate::messages::{payload_schemas, TypedMethod, DEFERRED_RESULTS, TYPED_METHODS};
use crate::methods::MethodName;
use crate::notifications::NotificationName;
use crate::{CANCEL_METHOD, HANDSHAKE_METHOD, JSONRPC_VERSION};

macro_rules! regenerate_command {
    () => {
        "cargo run --manifest-path src-tauri/Cargo.toml -p bridge-protocol --bin generate-protocol-artifacts"
    };
}

/// What to run when an artifact is stale. Shares the macro with the generated
/// header, so what a reader is told and what a failing test prints cannot
/// disagree.
#[cfg(test)]
const REGENERATE: &str = regenerate_command!();

const GENERATED_HEADER: &str = concat!(
    "GENERATED by bridge-protocol — do not edit.\nRegenerate: ",
    regenerate_command!()
);

/// A repo-relative path plus the exact content that belongs there.
pub struct Artifact {
    pub path: &'static str,
    pub content: String,
}

/// The envelope and handshake shapes, which belong to no method domain.
fn envelope_schemas() -> Vec<(&'static str, Value)> {
    vec![
        ("RpcRequest", serde_json::to_value(schema_for!(RpcRequest)).unwrap()),
        ("RpcResponse", serde_json::to_value(schema_for!(RpcResponse)).unwrap()),
        ("RpcNotification", serde_json::to_value(schema_for!(RpcNotification)).unwrap()),
        ("CancelParams", serde_json::to_value(schema_for!(CancelParams)).unwrap()),
        ("HandshakeRequest", serde_json::to_value(schema_for!(HandshakeRequest)).unwrap()),
        ("HandshakeResponse", serde_json::to_value(schema_for!(HandshakeResponse)).unwrap()),
    ]
}

fn root_schemas() -> Vec<(&'static str, Value)> {
    let mut roots = envelope_schemas();
    roots.extend(payload_schemas());
    // Voice is a transient notification rather than a method result. Generate
    // its payload too so clients cannot drift on owner IDs or partial semantics.
    roots.push(("VoiceTranscriptEvent", serde_json::to_value(
        schema_for!(crate::messages::VoiceTranscriptEvent)
    ).unwrap()));
    for (name, schema) in &mut roots {
        if let Some(object) = schema.as_object_mut() {
            // schemars titles transparent wrappers after their inner type
            // (e.g. Array_of_String); the registry name IS the contract, so
            // force it — generators keying on title must see the public name.
            object.insert("title".into(), Value::String((*name).into()));
        }
    }
    roots
}

/// The schema artifact filename for a registry type name.
fn schema_file(type_name: &str) -> String {
    format!("{}.json", kebab(type_name))
}

fn kebab(name: &str) -> String {
    let mut out = String::new();
    for (index, character) in name.chars().enumerate() {
        if character.is_ascii_uppercase() {
            if index > 0 {
                out.push('-');
            }
            out.push(character.to_ascii_lowercase());
        } else {
            out.push(character);
        }
    }
    out
}

fn methods_table() -> Value {
    json!({
        "$comment": GENERATED_HEADER,
        "protocolVersion": PROTOCOL_VERSION,
        "reserved": { "handshake": HANDSHAKE_METHOD, "cancel": CANCEL_METHOD },
        "methods": MethodName::ALL.iter().map(|method| {
            let mut entry = json!({
                "method": method.as_str(),
                "domain": method.domain(),
                "command": method.command_name(),
            });
            // Non-TypeScript clients discover payload contracts here. Every
            // method carries paramsSchema: a schema file, or an explicit null
            // meaning "contracted to take no parameters". resultSchema is
            // absent while a method's result shape is still uncontracted.
            let typed = TypedMethod::for_method(*method);
            entry["paramsSchema"] = match typed.params {
                Some(params) => json!(schema_file(params)),
                None => Value::Null,
            };
            // Every result is a schema reference or a documented exception
            // naming the core DTO still to be mirrored — never silently
            // absent.
            match typed.result {
                Some(result) => entry["resultSchema"] = json!(schema_file(result)),
                None => {
                    let (_, deferred) = DEFERRED_RESULTS
                        .iter()
                        .find(|(deferred, _)| deferred == method)
                        .expect("coverage test: untyped results are documented exceptions");
                    entry["resultDeferred"] = json!(deferred);
                }
            }
            entry
        }).collect::<Vec<_>>(),
    })
}

fn notifications_table() -> Value {
    json!({
        "$comment": GENERATED_HEADER,
        "notifications": NotificationName::ALL.iter().map(|notification| json!({
            "notification": notification.as_str(),
            "delivery": notification.delivery().as_str(),
        })).collect::<Vec<_>>(),
    })
}

fn error_codes_table() -> Value {
    json!({
        "$comment": GENERATED_HEADER,
        "codes": ErrorCode::ALL.iter().map(|code| json!({
            "name": code.name(),
            "code": code.code(),
            "summary": code.summary(),
        })).collect::<Vec<_>>(),
    })
}

/// Every artifact this crate maintains in the repository.
pub fn artifacts() -> Vec<Artifact> {
    let mut artifacts = Vec::new();
    for (name, mut schema) in root_schemas() {
        if let Some(object) = schema.as_object_mut() {
            object.insert("$comment".into(), Value::String(GENERATED_HEADER.replace('\n', " ")));
        }
        let path: &'static str = Box::leak(
            format!("docs/protocol/schemas/{}", schema_file(name)).into_boxed_str(),
        );
        artifacts.push(Artifact { path, content: pretty(&schema) });
    }
    artifacts.push(Artifact {
        path: "docs/protocol/schemas/methods.json",
        content: pretty(&methods_table()),
    });
    artifacts.push(Artifact {
        path: "docs/protocol/schemas/notifications.json",
        content: pretty(&notifications_table()),
    });
    artifacts.push(Artifact {
        path: "docs/protocol/schemas/error-codes.json",
        content: pretty(&error_codes_table()),
    });
    artifacts.push(Artifact { path: "src/protocol/generated/protocol.ts", content: typescript() });
    artifacts
}

/// Serialize an artifact with object keys in a canonical order.
///
/// `serde_json::Map` keeps insertion order when *any* crate in the build
/// enables serde_json's `preserve_order`, and sorts keys when none does. Cargo
/// unifies features across the whole workspace, so which of the two a build
/// gets depends on the dependencies of unrelated crates — and a checked-in
/// artifact must not change its bytes because something elsewhere gained a
/// dependency. Sorting here pins the output under either resolution.
fn pretty(value: &Value) -> String {
    let mut text = serde_json::to_string_pretty(&canonical(value)).unwrap();
    text.push('\n');
    text
}

fn canonical(value: &Value) -> Value {
    match value {
        Value::Object(object) => {
            let mut entries: Vec<(&String, &Value)> = object.iter().collect();
            entries.sort_by(|(left, _), (right, _)| left.cmp(right));
            Value::Object(
                entries.into_iter().map(|(key, value)| (key.clone(), canonical(value))).collect(),
            )
        }
        Value::Array(items) => Value::Array(items.iter().map(canonical).collect()),
        other => other.clone(),
    }
}

// ---------------------------------------------------------------------------
// JSON Schema (draft-07, as emitted by schemars) → TypeScript
// ---------------------------------------------------------------------------

fn ts_type(schema: &Value) -> String {
    match schema {
        // `true` is the "any" schema (e.g. serde_json::Value fields).
        Value::Bool(true) => "unknown".into(),
        Value::Bool(false) => "never".into(),
        Value::Object(object) => ts_type_of_object(object),
        _ => "unknown".into(),
    }
}

fn ts_type_of_object(object: &Map<String, Value>) -> String {
    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        return reference.rsplit('/').next().unwrap_or("unknown").into();
    }
    if let Some(members) = object.get("anyOf").or_else(|| object.get("oneOf")).and_then(Value::as_array) {
        let union: Vec<String> = members.iter().map(ts_type).collect();
        return union.join(" | ");
    }
    // schemars wraps doc-commented $ref fields in a single-member allOf.
    if let Some(members) = object.get("allOf").and_then(Value::as_array) {
        let intersection: Vec<String> = members.iter().map(ts_type).collect();
        return intersection.join(" & ");
    }
    if let Some(literals) = object.get("enum").and_then(Value::as_array) {
        let union: Vec<String> = literals
            .iter()
            .map(|literal| serde_json::to_string(literal).unwrap())
            .collect();
        return union.join(" | ");
    }
    if let Some(literal) = object.get("const") {
        return serde_json::to_string(literal).unwrap();
    }
    match object.get("type") {
        Some(Value::String(kind)) => scalar(kind, object),
        Some(Value::Array(kinds)) => {
            let union: Vec<String> =
                kinds.iter().filter_map(Value::as_str).map(|kind| scalar(kind, object)).collect();
            union.join(" | ")
        }
        _ => "unknown".into(),
    }
}

fn scalar(kind: &str, object: &Map<String, Value>) -> String {
    match kind {
        "string" => "string".into(),
        "integer" | "number" => "number".into(),
        "boolean" => "boolean".into(),
        "null" => "null".into(),
        "array" => {
            let item = object.get("items").map(ts_type).unwrap_or_else(|| "unknown".into());
            if item.contains('|') {
                format!("({item})[]")
            } else {
                format!("{item}[]")
            }
        }
        "object" => object_literal(object),
        _ => "unknown".into(),
    }
}

fn object_literal(object: &Map<String, Value>) -> String {
    let properties = object.get("properties").and_then(Value::as_object);
    if properties.map_or(true, Map::is_empty) {
        let value = object
            .get("additionalProperties")
            .map(ts_type)
            .unwrap_or_else(|| "unknown".into());
        return format!("Record<string, {value}>");
    }
    let properties = properties.unwrap();
    let required: Vec<&str> = object
        .get("required")
        .and_then(Value::as_array)
        .map(|entries| entries.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let fields: Vec<String> = properties
        .iter()
        .map(|(name, schema)| {
            let optional = if required.contains(&name.as_str()) { "" } else { "?" };
            format!("{name}{optional}: {}", ts_type(schema))
        })
        .collect();
    format!("{{ {} }}", fields.join("; "))
}

fn declaration(name: &str, schema: &Value) -> String {
    let is_plain_object = schema
        .as_object()
        .is_some_and(|object| object.get("properties").is_some() && object.get("$ref").is_none());
    if is_plain_object {
        let object = schema.as_object().unwrap();
        let properties = object.get("properties").and_then(Value::as_object).unwrap();
        let required: Vec<&str> = object
            .get("required")
            .and_then(Value::as_array)
            .map(|entries| entries.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();
        let mut lines = vec![format!("export interface {name} {{")];
        for (field, field_schema) in properties {
            let optional = if required.contains(&field.as_str()) { "" } else { "?" };
            lines.push(format!("  {field}{optional}: {};", ts_type(field_schema)));
        }
        lines.push("}".into());
        lines.join("\n")
    } else {
        format!("export type {name} = {};", ts_type(schema))
    }
}

/// The complete generated TypeScript module.
pub fn typescript() -> String {
    let mut definitions: BTreeMap<String, Value> = BTreeMap::new();
    let mut roots: Vec<(String, Value)> = Vec::new();
    for (name, schema) in root_schemas() {
        let mut object = schema.as_object().cloned().unwrap();
        if let Some(nested) = object.remove("definitions").and_then(|value| value.as_object().cloned()) {
            for (definition_name, definition) in nested {
                if let Some(existing) = definitions.get(&definition_name) {
                    assert_eq!(
                        existing, &definition,
                        "conflicting schema definitions for {definition_name}"
                    );
                } else {
                    definitions.insert(definition_name, definition);
                }
            }
        }
        for meta in ["$schema", "title", "$comment"] {
            object.remove(meta);
        }
        roots.push((name.to_string(), Value::Object(object)));
    }

    let mut out = String::new();
    for line in GENERATED_HEADER.lines() {
        out.push_str("// ");
        out.push_str(line);
        out.push('\n');
    }
    out.push('\n');
    out.push_str(&format!(
        "export const PROTOCOL_VERSION = {{ major: {}, minor: {} }} as const;\n",
        PROTOCOL_VERSION.major, PROTOCOL_VERSION.minor
    ));
    out.push_str(&format!("export const JSONRPC_VERSION = \"{JSONRPC_VERSION}\" as const;\n"));
    out.push_str(&format!("export const HANDSHAKE_METHOD = \"{HANDSHAKE_METHOD}\" as const;\n"));
    out.push_str(&format!("export const CANCEL_METHOD = \"{CANCEL_METHOD}\" as const;\n\n"));

    let method_literals: Vec<String> =
        MethodName::ALL.iter().map(|method| format!("  | \"{}\"", method.as_str())).collect();
    out.push_str("export type BridgeMethod =\n");
    out.push_str(&method_literals.join("\n"));
    out.push_str(";\n\n");

    out.push_str("export const BRIDGE_METHODS = [\n");
    for method in MethodName::ALL {
        out.push_str(&format!(
            "  {{ method: \"{}\", domain: \"{}\", command: \"{}\" }},\n",
            method.as_str(),
            method.domain(),
            method.command_name()
        ));
    }
    out.push_str("] as const;\n\n");

    let notification_literals: Vec<String> = NotificationName::ALL
        .iter()
        .map(|notification| format!("  | \"{}\"", notification.as_str()))
        .collect();
    out.push_str("export type BridgeNotification =\n");
    out.push_str(&notification_literals.join("\n"));
    out.push_str(";\n\n");
    out.push_str("export const BRIDGE_NOTIFICATIONS = [\n");
    for notification in NotificationName::ALL {
        out.push_str(&format!(
            "  {{ notification: \"{}\", delivery: \"{}\" }},\n",
            notification.as_str(),
            notification.delivery().as_str()
        ));
    }
    out.push_str("] as const;\n\n");

    out.push_str("export const ERROR_CODES = {\n");
    for code in ErrorCode::ALL {
        out.push_str(&format!("  {}: {},\n", code.name(), code.code()));
    }
    out.push_str("} as const;\n\n");

    out.push_str("/** Params types for methods whose payloads are contracted so far. */\n");
    out.push_str("export interface BridgeMethodParams {\n");
    for entry in TYPED_METHODS {
        out.push_str(&format!(
            "  \"{}\": {};\n",
            entry.method.as_str(),
            entry.params.unwrap_or("undefined")
        ));
    }
    out.push_str("}\n\n");
    out.push_str("/** Result types for every registered method. */\n");
    out.push_str("export interface BridgeMethodResults {\n");
    for method in MethodName::ALL {
        let entry = TypedMethod::for_method(*method);
        out.push_str(&format!(
            "  \"{}\": {};\n",
            method.as_str(),
            entry.result.unwrap_or("unknown")
        ));
    }
    out.push_str("}\n");

    for (name, schema) in &definitions {
        out.push('\n');
        out.push_str(&declaration(name, schema));
        out.push('\n');
    }
    for (name, schema) in &roots {
        if let Some(definition) = definitions.get(name) {
            assert_eq!(
                declaration(name, schema),
                declaration(name, definition),
                "root and nested schema disagree for {name}"
            );
            continue;
        }
        out.push('\n');
        out.push_str(&declaration(name, schema));
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn converter_handles_the_schema_subset_the_contract_uses() {
        assert_eq!(ts_type(&json!(true)), "unknown");
        assert_eq!(ts_type(&json!({"type": "string"})), "string");
        assert_eq!(ts_type(&json!({"type": "string", "const": "2.0"})), "\"2.0\"");
        assert_eq!(
            ts_type(&json!({"type": ["object", "array"]})),
            "Record<string, unknown> | unknown[]"
        );
        assert_eq!(ts_type(&json!({"type": "integer", "format": "int64"})), "number");
        assert_eq!(ts_type(&json!({"type": ["integer", "null"]})), "number | null");
        assert_eq!(ts_type(&json!({"$ref": "#/definitions/RequestId"})), "RequestId");
        assert_eq!(
            ts_type(&json!({"allOf": [{"$ref": "#/definitions/RequestId"}], "description": "d"})),
            "RequestId"
        );
        assert_eq!(
            ts_type(&json!({"anyOf": [{"$ref": "#/definitions/RpcError"}, {"type": "null"}]})),
            "RpcError | null"
        );
        assert_eq!(ts_type(&json!({"type": "array", "items": {"type": "string"}})), "string[]");
        assert_eq!(
            ts_type(&json!({"type": "array", "items": {"type": ["string", "null"]}})),
            "(string | null)[]"
        );
        assert_eq!(ts_type(&json!({"enum": ["a", "b"]})), "\"a\" | \"b\"");
        assert_eq!(
            ts_type(&json!({"type": "object", "additionalProperties": {"type": "boolean"}})),
            "Record<string, boolean>"
        );
    }

    #[test]
    fn generated_typescript_declares_the_full_contract() {
        let typescript = typescript();
        assert!(typescript.contains("export interface RpcRequest {"));
        assert!(typescript.contains("export interface HandshakeResponse {"));
        assert!(typescript.contains("export type RequestId = "));
        assert!(typescript.contains("export type JsonRpcVersion = \"2.0\";"));
        assert!(typescript.contains("export type Params = Record<string, unknown> | unknown[];"));
        assert!(
            typescript.contains("export type RpcResponse = RpcSuccess | RpcFailure;"),
            "responses must be a success/failure union, not an interface with optional outcomes"
        );
        assert!(typescript.contains("export type ResponseId = RequestId | null;"));
        assert!(typescript.contains("\"sessions/send_turn\""));
        assert!(typescript.contains("incompatible_protocol: 2000,"));
        assert!(typescript.contains("export type BridgeNotification ="));
        assert!(typescript.contains("{ notification: \"agent-event\", delivery: \"mixed\" },"));
        assert!(typescript.contains("{ notification: \"session-output\", delivery: \"transient\" },"));
        assert!(typescript.contains("export interface BridgeMethodParams {"));
        assert!(typescript
            .contains("\"workspaces/connect_workspace_folder\": ConnectWorkspaceFolderParams;"));
        assert!(typescript
            .contains("\"workspaces/list_workspace_files\": ListWorkspaceFilesResult;"));
        assert!(
            typescript.contains("\"sessions/refresh_account_usage\": undefined;"),
            "parameterless methods appear in the map with type undefined"
        );
        for method in [
            "sessions/interrupt_turn",
            "sessions/compact_session",
            "sessions/refresh_account_usage",
        ] {
            assert!(
                typescript.contains(&format!("\"{method}\": UnitResult;")),
                "unit-returning method {method} has an explicit result contract"
            );
        }
        assert!(typescript.contains("export interface ConnectWorkspaceFolderParams {"));
        assert!(typescript.contains("export type ListWorkspaceFilesResult = string[];"));
        assert!(typescript.contains(
            "\"sessions/replay_session_events\": ReplaySessionEventsResult;"
        ));
        assert!(typescript.contains("export type ReplaySessionEventsResult = ReplaySessionEvent[];"));
        assert!(typescript.contains("export type UnitResult = null;"));
        for method in MethodName::ALL {
            assert!(
                typescript.contains(&format!(
                    "\"{}\": {};",
                    method.as_str(),
                    TypedMethod::for_method(*method).result.unwrap_or("unknown")
                )),
                "BridgeMethodResults is missing {}",
                method.as_str()
            );
        }
        assert!(typescript.contains("harnesses: Record<string, boolean>;"));
    }

    #[test]
    fn generated_typescript_exports_each_declaration_once() {
        let typescript = typescript();
        let mut declarations = std::collections::BTreeSet::new();
        for line in typescript.lines() {
            let tail = line
                .strip_prefix("export interface ")
                .or_else(|| line.strip_prefix("export type "));
            let Some(name) = tail.and_then(|tail| tail.split([' ', '=']).next()) else {
                continue;
            };
            assert!(
                declarations.insert(name.to_owned()),
                "duplicate TypeScript declaration for {name}"
            );
        }
    }

    #[test]
    fn every_schema_root_keeps_its_registry_title() {
        // Transparent wrappers would otherwise inherit their inner type's
        // title (Array_of_String) and collide across future array results.
        for (name, schema) in root_schemas() {
            assert_eq!(
                schema["title"], serde_json::json!(name),
                "schema for {name} must be titled with its registry name"
            );
        }
    }

    #[test]
    fn every_method_row_references_a_generated_schema_artifact() {
        let table = methods_table();
        let artifact_paths: Vec<String> =
            artifacts().into_iter().map(|artifact| artifact.path.to_string()).collect();
        let rows = table["methods"].as_array().unwrap();
        assert_eq!(rows.len(), MethodName::ALL.len());
        for row in rows {
            let method = row["method"].as_str().unwrap();
            let typed = TYPED_METHODS
                .iter()
                .find(|typed| typed.method.as_str() == method)
                .unwrap_or_else(|| panic!("{method} is not contracted"));
            assert!(
                row.get("paramsSchema").is_some(),
                "{method} must carry paramsSchema — a file reference or an explicit null"
            );
            match typed.params {
                Some(expected) => {
                    let params = row["paramsSchema"].as_str().unwrap();
                    assert_eq!(params, schema_file(expected));
                    assert!(
                        artifact_paths.contains(&format!("docs/protocol/schemas/{params}")),
                        "{method} references {params}, which is not a generated artifact"
                    );
                }
                None => assert!(
                    row["paramsSchema"].is_null(),
                    "{method} is contracted parameterless; paramsSchema must be null"
                ),
            }
            match typed.result {
                Some(result) => {
                    let result_file = row["resultSchema"].as_str().unwrap();
                    assert_eq!(result_file, schema_file(result));
                    assert!(
                        artifact_paths.contains(&format!("docs/protocol/schemas/{result_file}"))
                    );
                }
                None => assert!(
                    row.get("resultSchema").is_none(),
                    "{method} has no contracted result; resultSchema must be absent"
                ),
            }
        }
    }

    #[test]
    fn every_root_schema_round_trips_an_example_through_serde() {
        // The schemas describe exactly what serde emits; spot-check that the
        // envelope examples deserialize from their serialized form (the full
        // per-type round-trip tests live next to each type).
        let request = RpcRequest::new(
            crate::RequestId::Number(1),
            MethodName::SendTurn.as_str(),
            Some(crate::Params::new(json!({"sessionId": "s", "text": "hello"})).unwrap()),
        );
        let encoded = serde_json::to_string(&request).unwrap();
        assert_eq!(serde_json::from_str::<RpcRequest>(&encoded).unwrap(), request);
    }

    #[test]
    fn checked_in_artifacts_match_the_contract() {
        for artifact in artifacts() {
            let path = repository_root().join(artifact.path);
            let checked_in = std::fs::read_to_string(&path).unwrap_or_else(|error| {
                panic!("{} is missing ({error}) — run: {REGENERATE}", artifact.path)
            });
            assert_eq!(
                checked_in, artifact.content,
                "{} is stale — run: {REGENERATE}",
                artifact.path
            );
        }
    }

    #[test]
    fn no_orphaned_schema_files_linger_in_the_repository() {
        // A renamed payload type would otherwise leave its old schema behind,
        // where a non-TypeScript client could still be reading it.
        let generated: Vec<String> =
            artifacts().into_iter().map(|artifact| artifact.path.to_string()).collect();
        let directory = repository_root().join("docs/protocol/schemas");
        for entry in std::fs::read_dir(&directory).unwrap() {
            let file = entry.unwrap().file_name().to_string_lossy().to_string();
            let path = format!("docs/protocol/schemas/{file}");
            assert!(
                generated.contains(&path),
                "{path} is checked in but no longer generated — delete it and run: {REGENERATE}"
            );
        }
    }

    /// Artifact paths are repository-relative; resolve them from the crate
    /// manifest so the test does not depend on the working directory.
    fn repository_root() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
    }
}
